// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/uapi-go-operator/pkg/apis/uiapi/v1alpha1.Uapi":       schema_pkg_apis_uiapi_v1alpha1_Uapi(ref),
		"github.com/uapi-go-operator/pkg/apis/uiapi/v1alpha1.UapiSpec":   schema_pkg_apis_uiapi_v1alpha1_UapiSpec(ref),
		"github.com/uapi-go-operator/pkg/apis/uiapi/v1alpha1.UapiStatus": schema_pkg_apis_uiapi_v1alpha1_UapiStatus(ref),
	}
}

func schema_pkg_apis_uiapi_v1alpha1_Uapi(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Uapi is the Schema for the uapis API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/uapi-go-operator/pkg/apis/uiapi/v1alpha1.UapiSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/uapi-go-operator/pkg/apis/uiapi/v1alpha1.UapiStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/uapi-go-operator/pkg/apis/uiapi/v1alpha1.UapiSpec", "github.com/uapi-go-operator/pkg/apis/uiapi/v1alpha1.UapiStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_uiapi_v1alpha1_UapiSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "UapiSpec defines the desired state of Uapi",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_uiapi_v1alpha1_UapiStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "UapiStatus defines the observed state of Uapi",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
